<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PendaftarController;
use App\Http\Controllers\BerkasController;

// Default page
Route::get('/', function () {
    return view('welcome');
});

// Authenticated user routes
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Admin routes
Route::middleware(['auth', 'role:ADMIN'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');
    Route::post('/pendaftar/{id}/approve', [AdminController::class, 'approvePendaftar'])->name('approve');
    Route::post('/pendaftar/{id}/reject', [AdminController::class, 'rejectPendaftar'])->name('reject');
    Route::put('/profile', [AdminController::class, 'updateProfile'])->name('updateProfile');
    Route::post('/password', [AdminController::class, 'updatePassword'])->name('updatePassword');
    Route::get('/pendaftar/{id}/edit', [AdminController::class, 'edit'])->name('edit');
    Route::put('/pendaftar/{id}/update', [AdminController::class, 'update'])->name('admin.update');
    Route::delete('/pendaftar/{id}', [AdminController::class, 'destroy'])->name('delete'); // << ini route delete
    // CRUD admin
Route::get('create', [AdminController::class, 'create'])->name('create');
Route::post('store', [AdminController::class, 'store'])->name('store');
Route::get('edit/{id}', [AdminController::class, 'editAdmin'])->name('edit');
Route::put('/{id}/update', [AdminController::class, 'updateAdmin'])->name('update');
Route::delete('delete/{id}', [AdminController::class, 'destroyAdmin'])->name('destroy');

});


// Pendaftar routes
Route::middleware(['auth', 'role:PENDAFTAR'])->prefix('pendaftar')->name('pendaftar.')->group(function () {
    Route::get('/dashboard', [PendaftarController::class, 'index'])->name('dashboard');
    Route::post('/update', [PendaftarController::class, 'update'])->name('update');
    Route::post('/upload-berkas', [PendaftarController::class, 'uploadBerkas'])->name('uploadBerkas');
    Route::post('/upload-prestasi', [PendaftarController::class, 'uploadPrestasi'])->name('uploadPrestasi');
// Halaman persyaratan dan ketentuan
 // ✅ Tambahkan route hapus prestasi
    Route::delete('/prestasi/{id}', [PendaftarController::class, 'hapusPrestasi'])->name('hapusPrestasi');
   Route::get('terms', [PendaftarController::class, 'terms'])->name('terms');
Route::delete('/berkas/{jenis}', [PendaftarController::class, 'hapusBerkas'])->name('hapusBerkas');

  // ✅ Tambahkan route untuk profil pendaftar
    Route::get('/profile', [PendaftarController::class, 'editProfile'])->name('editProfile');
    Route::put('/profile', [PendaftarController::class, 'updateProfile'])->name('updateProfile');
    // Tambahkan route PDF
    Route::get('/dashboard/pdf', [PendaftarController::class, 'exportPdf'])->name('dashboard.pdf');
});


// Auth routes (generated by Breeze/Fortify/etc.)
require __DIR__.'/auth.php';
